In [1]:
import numpy as np

In [2]:
#sayısal işlemler list tipine göre daha avantajlıdır

In [3]:
liste=[1,2,3,4,5]

In [4]:
numpy_list=np.array(liste)

In [5]:
#aritmetik işlemleri açısından kolaylık sağlar listede olmayan birçok method var

In [6]:
liste2=[6,7,8,9,10]
numpy_list2=np.array(liste2)

In [7]:
numpy_list+numpy_list2 #toplama işlemi normal liste toplamadan farklıdır

array([ 7,  9, 11, 13, 15])

In [9]:
numpy_list**2 #çarpma işlemide farklıdır

array([ 1,  4,  9, 16, 25])

In [19]:
np.square(numpy_list)

array([ 1,  4,  9, 16, 25])

In [13]:
np_list=np.arange(0,20,2)

In [15]:
np.random.randint(1,300,5) #1'den 300'e kadar 5 adet integer sayı

array([216,  49, 297, 276,   1])

In [17]:
np.random.randn(3,3) #3'e 3'lük bir matris

array([[-0.10334128,  0.49722522, -0.8690504 ],
       [-0.32967443,  0.76832368,  0.06596127],
       [-0.11186056, -0.71022304,  2.27600817]])

MATRİXLER VE İŞLEMLERİ

In [26]:
matrix_1=np.random.random((2,3))

In [27]:
matrix_2=np.random.random((3,4))

In [28]:
# dot product matrisleri çarpma işlemi ->!yapılması için ilk matrisin sütun değeri ile çarpma yapılacak olanın
#kolon değeri aynı olmalı

In [29]:
#matrix_1*matrix_2 yapılmaz ancak dotproduct yapılabilir

In [31]:
np.dot(matrix_1,matrix_2)

array([[0.60574789, 0.28493966, 0.33236002, 0.88583034],
       [0.9231346 , 0.92265334, 0.57383437, 0.99326525]])

OTHER EXAMPLE

In [32]:
np_array=np.random.randint(0,100,7)

In [33]:
np_array[np_array>10] #boolean değerleri dizi içine verme

array([61, 21, 25, 76, 59, 97, 58])

In [35]:
np_array_1=np.random.random((6,1))

In [36]:
np_array_1.reshape(3,2)

array([[0.77676116, 0.57279342],
       [0.95941913, 0.13369769],
       [0.1065751 , 0.67537901]])

In [37]:
#z-score

In [41]:
z_score_list=np.array([10,20,30,45,44,33,55,300,321])

In [44]:
mean=np.mean(z_score_list)

In [45]:
std=np.std(z_score_list)

In [46]:
z_score=(z_score-mean)/std

In [48]:
z_score #outlier olan verilerin z_scoreleri büyük cıktı tespit etme işlemi aşağıda

array([-0.73680125, -0.65045735, -0.56411345, -0.43459761, -0.443232  ,
       -0.53821029, -0.34825371,  1.76717174,  1.94849392])

In [49]:
z_score_list[z_score>1]

array([300, 321])

In [51]:
#lineer cebir çözmü
#5x+3y=21 ve 3x+8y=39

In [52]:
#coefficient
A=np.array([[5,3],[3,8]])
#constant
B=np.array([21,39])

In [53]:
solution=np.linalg.solve(A,B)

In [54]:
solution

array([1.64516129, 4.25806452])